# Generated by Django 4.0.6 on 2022-07-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('age', models.DurationField()),
                ('gender', models.TextField()),
                ('password', models.TextField()),
                ('course', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
